[project]
name = "tools"
version = "0.1.0"
description = "Gathering of different small tools used throughout S-CORE"
readme = "README.md"
requires-python = ">=3.12"

[tool.uv.workspace]
members = [
    "cr_checker",
    "repo_policy_sync",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "cr-checker",
    "pyfakefs>=6.1.6",
    "pytest>=9.1.1",
    "repo-policy-sync",
    "ruff==0.15.10",
]

[tool.uv.sources]
cr-checker = { workspace = true }
repo-policy-sync = { workspace = true }

[tool.pytest.ini_options]

norecursedirs = [
    ".*",        # hidden folders like .git, .venv, .cache, etc.
    "bazel-*",   # Bazel output folders
]
