# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

module(name = "example")
bazel_dep(name = "score_platform", version = "0.7.0")
bazel_dep(name = "score_docs_as_code", version = "8.0.0")
bazel_dep(name = "score_process_description", version = "2.1.1")
